### PR TITLE
Delete unnecessary first commits

### PR DESCRIPTION
**Pull request by l1storez**
After a long break, decided to do smth simple to test the new configuration. Removed(squashed) empty and unnecessary 7 commits at the beginning of the branch. I think almost everything works

-----
[View rendered LICENSE.md](https://github.com/kpi-web-guild/django-girls-blog-l1storez/blob/bugfixes/delete-unnecessary-commits/LICENSE.md)
[View rendered README.md](https://github.com/kpi-web-guild/django-girls-blog-l1storez/blob/bugfixes/delete-unnecessary-commits/README.md)

### CODE REVIEW

**Comment by webknjaz** [comment]
You know there's no such thing as deleting commits, right?

**Comment by l1storez** [comment]
Yep, I squashed 8 commits into 1. I forgot about the naming, sorry

**Comment by webknjaz** [comment]
Old commits will remain in the tree, though.

**Review by webknjaz — APPROVED** [review]

**Comment by l1storez** [comment]
Okay

**Pull request merged**
